# @package _global_

num_steps: 50_000 
env: CartPole-v1
env_kwargs: {}
env_wrappers: []

# >>>>>>>>>>> tuned
algorithm_kwargs:
  batch_size: 64
  epsilon: 0.08891452327939459
  learning_rate: 0.00034166730122874765
  n_units: 25
  soft_update_weight: 0.014181646517035525
  td_update_class: coax.td_learning.QLearning