# In order to use this sweeper, add on the commandline:
# +sweeper=smac +search_space=mighty_template

defaults:
  - override hydra/sweeper: SMAC

cluster:
  _target_: dask_jobqueue.SLURMCluster
  queue: cpu_short  # partition
  #  account: myaccount
  cores: 1
  memory: 1 GB
  walltime: 00:30:00
  processes: 1
  log_directory: tmp/smac_dask_slurm

hydra:
  sweeper:
    smac_class: smac.facade.blackbox_facade.BlackBoxFacade
    scenario:
      seed: 42
      n_trials: 100
      deterministic: true
      n_workers: 2
    smac_kwargs:
      dask_client:
        _target_: dask.distributed.Client
        address: ${create_cluster:${cluster},${hydra.sweeper.scenario.n_workers}}