# @package hydra.sweeper.search_space
hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-3
    log: true
    default_value: 1e-2
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0.01
    upper: 0.25
    default_value: 0.1
  algorithm_kwargs.batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
    default_value: 64
  algorithm_kwargs.n_units:
    type: categorical
    choices: [5, 50, 75, 150, 200]
    default_value: 75
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 0.001
    upper: 1.0
    log: true
    default_value: 1e-2
  algorithm_kwargs.td_update_class:
    type: categorical
    choices: [coax.td_learning.QLearning, coax.td_learning.DoubleQLearning, coax.td_learning.SoftQLearning] #, coax.td_learning.ClippedDoubleQLearning, coax.td_learning.SoftClippedDoubleQLearning]
    default_value: coax.td_learning.DoubleQLearning

