# @package hydra.sweeper.search_space
hyperparameters:
  algorithm_kwargs.n_units:
    type: ordinal
    sequence: [4,8,16,32,64,128,256,512]
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 0
    upper: 1
    default_value: 1

