hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-2
    log: true
    default_value: 5e-3
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0.01
    upper: 0.25
    default_value: 0.1
  algorithm_kwargs.batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
    default_value: 32
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 0.01
    upper: 1.0
    log: true
    default_value: 1.
  algorithm_kwargs.td_update_class:
    type: categorical
    choices: [mighty.mighty_update.QLearning, mighty.mighty_update.DoubleQLearning] #, coax.td_learning.ClippedDoubleQLearning, coax.td_learning.SoftClippedDoubleQLearning]
    default_value: mighty.mighty_update.DoubleQLearning

