hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-3
    log: true
    default_value: 1e-2
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0.01
    upper: 0.25
    default_value: 0.1
  algorithm_kwargs.batch_size:
    type: categorical
    choices: {32, 64, 128, 256}
    default_value: 64
  algorithm_kwargs.n_units:
    type: categorical
    choices: {25, 50, 75, 150, 200}
    default_value: 75
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 0.001
    upper: 1.0
    log: true
    default_value: 1e-2
  algorithm_kwargs.td_update_class:
    type: categorical
    choices: {q, double, soft, clipped, softclipped} # no idea if that is the right way to set these
    defualt_value: double

