# @package hydra.sweeper.search_space

# Possible HP types:
# constant, unparametrized, uniform_float, normal_float, beta_float
# uniform_int, normal_int, beta_int, categorical, ordinal
hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-2
    log: true
    default_value: 1e-3
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0
    upper: 1
    log: false
    default_value: 0.1
  algorithm_kwargs.batch_size:
    type: ordinal
    sequence: [4,8,16,32,64,128,256,512,1024]
    default: 64