hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-3
    log: true
    default_value: 1e-4
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0.01
    upper: 0.25
    default_value: 0.05
  algorithm_kwargs.batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
    default_value: 128
  algorithm_kwargs.n_policy_units:
    type: categorical
    choices: [10, 25, 50]
    default_value: 25
  algorithm_kwargs.n_critic_units:
    type: categorical
    choices: [10, 25, 50, 75]
    default_value: 25
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 0.01
    upper: 1.0
    log: false
    default_value: .25
  algorithm_kwargs.clip:
    type: uniform_float
    lower: 0.2
    upper: 0.4
    log: false
    default_value: 0.2

