hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 1e-6
    upper: 1e-2
    log: true
    default_value: 1e-4
  algorithm_kwargs.epsilon:
    type: uniform_float
    lower: 0.01
    upper: 0.25
    default_value: 0.05
  algorithm_kwargs.batch_size:
    type: categorical
    choices: {32, 64, 128, 256, 512}
    default_value: 256
  algorithm_kwargs.n_policy_units:
    type: categorical
    choices: {64, 128, 256, 512}
    default_value: 256
  algorithm_kwargs.n_critic_units:
    type: categorical
    choices: {32, 64, 128, 256}
    default_value: 128
  algorithm_kwargs.soft_update_weight:
    type: uniform_float
    lower: 1e-5
    upper: 5e-3
    log: true
    default_value: 5e-3
  algorithm_kwargs.td_update_class:
    type: categorical
    choices: {q, double, soft, clipped, softclipped} # no idea if that is the right way to set these
    defualt_value: double