# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: normal
    cpus_per_task: 1
    name: expl2
    timeout_min: 20
    mem_gb: 4
    setup:
      - micromamba activate /scratch/hpc-prf-intexml/cbenjamins/envs/mighty

cluster:
  queue: normal  # partition
