defaults:
  - _self_
  - algorithm: dqn
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/help: mighty_help

debug: false
seed: 0
output_dir: runs/training
wandb_project: null
tensorboard_file: null
experiment_name: mighty_experiment

algorithm_kwargs: {}

num_steps: ???  # Number of training steps
env: ???
env_kwargs: ???
env_wrappers: ???

# Training
eval_every_n_steps: 1000  # After how many steps to evaluate.
n_episodes_eval: null
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5000


hydra:
  run:
    dir: ${output_dir}/${experiment_name}_${seed}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}/${now:%Y-%m-%d}/${now:%H-%M-%S}
