defaults:
  - slurm
  - _self_
  - help: mighty_help
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

debug: false
seed: 0
group: null
output_dir: /tmp
wandb_project: null
tensorboard_file: null
experiment_name: "mighty_experiment"

algorithm: SAC
algorithm_kwargs: {}

num_steps: 1000000  # Maximum number of steps in the environment before episode ends.
env: CartPole-v0
env_kwargs: {}
env_wrappers: []

# Training
eval_every_n_steps: 1000  # After how many steps to evaluate.
n_episodes_eval: null
checkpoint: null  # Path to model checkpoint to load model from.


hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}