defaults:
  - slurm
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

debug: false
seed: 0
group: null
output_dir: ./tmp
wandb_id: null

num_steps: 1000000  # Maximum number of steps in the environment before episode ends.
env: CartPole-v0
env_kwargs: {}
env_wrappers: []

eval_every_n_steps: 1000  # After how many steps to evaluate.
checkpoint: null  # Path to model checkpoint to load model from.


hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}