defaults:
  - _self_
  - algorithm: bbfe_buffer_only
  - search_space: dqn_gym_classic
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/help: mighty_help
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ai,tnt
    cpus_per_task: 1
    mem_gb: 50
    timeout_min: 600
  run:
    dir: ${output_dir}/hydra/bbfe_buffer_comparison_${algorithm}_${env}/${seed}
  sweep:
    dir: ${output_dir}/bbfe_buffer_comparison_${algorithm}_${env}/${seed}

debug: false
seed: 0
output_dir: runs
wandb_project: null
tensorboard_file: null
experiment_name: bbfe_buffer_comparison

algorithm_kwargs: {}

num_envs: 8
num_steps: 50_000 
env: CartPole-v1
env_kwargs: {}
env_wrappers: []

# Training
eval_every_n_steps: 1e4  # After how many steps to evaluate.
n_episodes_eval: 10
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5e5

algorithm_kwargs.buffer_experiment: true
