defaults:
  - override hydra/launcher: submitit_slurm
hydra:
  launcher:
    partition: cpu_short  # gpu_normal
    #gres: gpu:1
    mem_gb: 12
    cpus_per_task: 20  # 6
    timeout_min: 720   # 1440  # 240
    setup:
      - export XLA_PYTHON_CLIENT_PREALLOCATE=false