# In order to use this sweeper, add on the commandline:
# +sweeper=smac +search_space=mighty_template

defaults:
  - _self_
  - algorithm: dqn
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/help: mighty_help
  - override hydra/sweeper: SMAC

cluster:
  _target_: dask_jobqueue.SLURMCluster
  queue: cpu_short  # partition
  #  account: myaccount
  cores: 1
  memory: 10 GB
  walltime: 01:00:00
  processes: 1
  log_directory: tmp/mighty_smac

hydra:
  run:
    dir: ${output_dir}/${experiment_name}_${seed}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    smac_class: smac.facade.blackbox_facade.BlackBoxFacade
    scenario:
      seed: 42
      n_trials: 100
      deterministic: true
      n_workers: 2
    smac_kwargs:
      dask_client:
        _target_: dask.distributed.Client
        address: ${create_cluster:${cluster},${hydra.sweeper.scenario.n_workers}}

debug: false
seed: 0
output_dir: /tmp
wandb_project: null
tensorboard_file: null
experiment_name: "mighty_experiment"

algorithm_kwargs: {}

num_steps: 1000000  # Maximum number of steps in the environment before episode ends.
env: CartPole-v1
env_kwargs: {}
env_wrappers: []

# Training
eval_every_n_steps: 1000  # After how many steps to evaluate.
n_episodes_eval: null
checkpoint: null  # Path to load model checkpoint