# This is a basic workflow to help you get started with Actions

name: Pytest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  #schedule:
  #  # Every Monday at 7AM UTC
  #  - cron: '0 07 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9]
        use-conda: [false]
        include:
          - python-version: 3.9
            code-cov: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      # A note on checkout: When checking out the repository that
      # triggered a workflow, this defaults to the reference or SHA for that event.
      # Otherwise, uses the default branch (master) is used.
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      if: matrix.use-conda == false
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
    - name: Store repository status
      id: status-before
      run: |
        echo "::set-output name=BEFORE::$(git status --porcelain -b)"
    - name: Run tests
      timeout-minutes: 45
      if: matrix.use-conda == false
      run: |
        if [ ${{ matrix.code-cov }} ]; then codecov='--cov=mighty --cov-report=xml'; fi
        pytest --durations=20 --timeout=300 --timeout-method=thread -v $codecov test
    - name: Check for files left behind by test
      if: ${{ always() }}
      run: |
        before="${{ steps.status-before.outputs.BEFORE }}"
        after="$(git status --porcelain -b)"
        if [[ "$before" != "$after" ]]; then
            echo "git status from before: $before"
            echo "git status from after: $after"
            echo "Not all generated files have been deleted!"
            exit 1
        fi
