# This is a basic workflow to help you get started with Actions

name: Pytest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  #schedule:
  #  # Every Monday at 7AM UTC
  #  - cron: '0 07 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest, ubuntu-18.04]
    strategy:
      matrix:
        python-version: [3.9]
        use-conda: [true, false]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      # A note on checkout: When checking out the repository that
      # triggered a workflow, this defaults to the reference or SHA for that event.
      # Otherwise, uses the default branch (master) is used.
      with:
        python-version: ${{ matrix.python-version }}
    - name: Conda Install test dependencies
      if: matrix.use-conda == true
      run: |
        # Miniconda is available in $CONDA env var
        $CONDA/bin/conda create -n testenv --yes python=${{ matrix.python-version }}
        $CONDA/envs/testenv/bin/python3 -m pip install --upgrade pip
        $CONDA/envs/testenv/bin/pip3 install pytorch torchvision torchaudio cpuonly -c pytorch -c=conda-forge
        $CONDA/envs/testenv/bin/pip3 install ignite -c pytorch
        $CONDA/envs/testenv/bin/pip3 install -r requirements.txt
        $CONDA/envs/testenv/bin/pip3 install pytest
        $CONDA/envs/testenv/bin/python3 setup.py develop
    - name: Install test dependencies
      if: matrix.use-conda == false
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        python setup.py develop
    - name: Store repository status
      id: status-before
      run: |
        echo "::set-output name=BEFORE::$(git status --porcelain -b)"
    - name: Conda Run tests
      timeout-minutes: 45
      if: matrix.use-conda == true
      run: |
        # We activate conda as metalearning uses python directly, so we need
        # to change the default python
        export PATH="$CONDA/envs/testenv/bin:$PATH"
        $CONDA/envs/testenv/bin/python3 -m pytest -v --cov=mighty --durations=20 --timeout=300 --timeout-method=thread test
    - name: Run tests
      timeout-minutes: 45
      if: matrix.use-conda == false
      run: |
        pytest -v --cov=mighty --durations=20 --timeout=300 --timeout-method=thread test
    - name: Check for files left behind by test
      if: ${{ always() }}
      run: |
        before="${{ steps.status-before.outputs.BEFORE }}"
        after="$(git status --porcelain -b)"
        if [[ "$before" != "$after" ]]; then
            echo "git status from before: $before"
            echo "git status from after: $after"
            echo "Not all generated files have been deleted!"
            exit 1
        fi
