
name: Tests

on:
  workflow_dispatch:  # Manually trigger the workflow
  # Triggers with push to main
  push:
    branches:
      - main
      - development

  # Triggers with push to a PR aimed at main
  pull_request:
    branches:
      - main
      - development

env:
  package-name: "mighty"
  test-dir: test
  extra-requires: "[dev,carl,pufferlib]"  # "" for no extra_requires

  # Arguments used for pytest
  pytest-args: >-
    --durations=20
    -v

jobs:

  # General unit tests
  source-test:
    name: test

    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash # Default to using bash on all

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install ${{ env.package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install dacbench
        python -m pip install -e ".${{ env.extra-requires }}"

    - name: Store git status
      id: status-before
      shell: bash
      run: |
        echo "::set-output name=BEFORE::$(git status --porcelain -b)"

    - name: Tests
      run: |
        python -m "import carl"
        python -m "from carl.envs import CARLBraxAnt"
        make test

    - name: Check for files left behind by test
      run: |
        before="${{ steps.status-before.outputs.BEFORE }}"
        after="$(git status --porcelain -b)"
        if [[ "$before" != "$after" ]]; then
            echo "git status from before: $before"
            echo "git status from after: $after"
            echo "Not all generated files have been deleted!"
            exit 1
        fi